name: Cypress Tests

on:
  push:
    branches:
      - christina-dev

jobs:
  test:
    runs-on: ubuntu-latest
    node-version: '16'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./horizon
        run: npm install

      - name: Start server and run tests
        working-directory: ./horizon
        run: npm run e2e:headless
