name: Cypress Tests

on:
  push:
    branches:
      - christina-dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ./horizon
        run: npm install

      - name: Start server and run tests
        working-directory: ./horizon
        run: npm run e2e:headless
